### ISSUE TITLE
Holding records are missing $x

### ISSUE THREAD

**Issue by ahankinson** [rism-international/muscat-maintenance#30]
@HirschSt When looking at the updated holdings scripts, and the holdings records that are being produced, I noticed that all the `852` fields are missing the `$x` field for the institution ID. Is it possible to also add that to your maintenance script? Thank you!

Tagging also @xhero

**Comment by xhero** [comment]
Yup Muscat gets a bit upset when I run the script:

```
Tag 852: missing master (expected in $x), tag contents: =852  ##$aGB-Lbl$cA.1107.p.
```

**Comment by HirschSt** [comment]
Alas, poor Muscat... sure, I will add $x then
